#Spring boot server config: application url
server:
  contextPath: /daj-ws

#Basic Spring Boot Config for Oracle
oracle:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@ora-7:1521:DEV
    username: daj
    password: root


portail-juridique:
  web-client-domain: http://localhost:4200
  sophia:
    ws-url: http://localhost:8080/get_producer_programs
    producer-programs-service: /get_producer_programs



